CREATE TABLE caixa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aberto_em TIMESTAMP NOT NULL,
    fechado_em TIMESTAMP,
    valor_abertura NUMERIC(10, 2) NOT NULL,
    valor_fechamento NUMERIC(10, 2),
    status VARCHAR(20) NOT NULL,
    operador_id BIGINT NOT NULL,

    CONSTRAINT ck_caixa_status CHECK (status IN ('ABERTO', 'FECHADO')),
    CONSTRAINT fk_caixa_operador
        FOREIGN KEY (operador_id) REFERENCES usuario (id)
);

CREATE INDEX idx_caixa_operador_id ON caixa (operador_id);
