CREATE TABLE produto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    codigo_barras VARCHAR(60),
    preco NUMERIC(10, 2) NOT NULL,
    ativo BOOLEAN NOT NULL,

    CONSTRAINT uk_produto_codigo_barras UNIQUE (codigo_barras),
    CONSTRAINT ck_produto_nome_nao_vazio CHECK (BTRIM(nome) <> ''),
    CONSTRAINT ck_produto_preco_nao_negativo CHECK (preco >= 0)
);
